runtime: python37

env_variables:
  PYTHONHTTPSVERIFY: 1


handlers:

- url: /static
  static_dir: static/
  secure: always

# Set Django admin to be login:admin as well as Django's is_staff restriction
- url: /admin.*
  script: auto
  secure: always

- url: /.*
  script: auto
  secure: always
